### PR TITLE
Go a bit faster

### PR DESCRIPTION
**Pull request by arter97**
Hooking up https://github.com/ssut/payload-dumper-go is probably an overkill for full OTA, but background downloads greatly help reducing total time.

### CODE REVIEW

**Comment by luk1337** [comment]
Not sure if we won't be hitting disk space issues when doing it this way. Can you try dumping https://github.com/luk1337/oplus_archive/releases/tag/LE2125_13.1.0.590(EX01) on actions with these changes?

**Comment by arter97** [comment]
Seems to cut it a bit close, 2.2G free.

https://github.com/arter97/nothing_archive/actions/runs/6160261491/job/16716791309#step:4:359

Yeah, this might be problematic for fat oplus firmware.
If you think other bigger base (full) oplus firmware can emerge, feel free to close this.

**Comment by luk1337** [comment]
Will probably add:

```
    - name: Run maximize-build-space
      uses: easimon/maximize-build-space@master
      with:
        remove-android: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
```

If I actually hit this issue at some point.

**Comment by arter97** [comment]
:+1:

**Pull request merged**
